"""
Pydantic v2 Schemas for the Advanced NIDS System.

Provides strongly-typed data models for all network data, alerts,
authentication, configuration, and API request/response contracts.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class AlertSeverity(str, Enum):
    """Severity levels for security alerts."""
    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class DetectionType(str, Enum):
    """Source engine that produced the detection."""
    ML = "ml"
    SIGNATURE = "signature"
    HYBRID = "hybrid"
    BEHAVIORAL = "behavioral"
    THREAT_INTEL = "threat_intel"


class AttackCategory(str, Enum):
    """High-level attack categories mapped to MITRE ATT&CK."""
    RECONNAISSANCE = "reconnaissance"
    INITIAL_ACCESS = "initial_access"
    EXECUTION = "execution"
    PERSISTENCE = "persistence"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    DEFENSE_EVASION = "defense_evasion"
    CREDENTIAL_ACCESS = "credential_access"
    DISCOVERY = "discovery"
    LATERAL_MOVEMENT = "lateral_movement"
    COLLECTION = "collection"
    COMMAND_AND_CONTROL = "command_and_control"
    EXFILTRATION = "exfiltration"
    IMPACT = "impact"
    UNKNOWN = "unknown"


class UserRole(str, Enum):
    """RBAC user roles."""
    ADMIN = "admin"
    ANALYST = "analyst"
    VIEWER = "viewer"


class IPSAction(str, Enum):
    """IPS response actions."""
    BLOCK = "block"
    THROTTLE = "throttle"
    REDIRECT = "redirect"
    ALERT_ONLY = "alert_only"



class PacketInfo(BaseModel):
    """Individual packet captured from the network."""
    model_config = ConfigDict(from_attributes=True)

    timestamp: datetime = Field(default_factory=datetime.now)
    source_ip: str
    dest_ip: str
    protocol: str
    source_port: Optional[int] = None
    dest_port: Optional[int] = None
    packet_length: int
    tcp_flags: Optional[str] = None
    payload_size: int = 0
    payload_hex: Optional[str] = None
    ttl: Optional[int] = None
    ip_version: int = 4
    vlan_id: Optional[int] = None


class NetworkFlow(BaseModel):
    """Aggregated bidirectional network flow (NetFlow/IPFIX-style)."""
    model_config = ConfigDict(from_attributes=True)

    flow_id: str
    start_time: datetime
    end_time: datetime
    source_ip: str
    dest_ip: str
    source_port: Optional[int] = None
    dest_port: Optional[int] = None
    protocol: str
    total_packets: int = 0
    total_bytes: int = 0
    forward_packets: int = 0
    backward_packets: int = 0
    forward_bytes: int = 0
    backward_bytes: int = 0
    duration_seconds: float = 0.0
    mean_inter_arrival_time: float = 0.0
    std_inter_arrival_time: float = 0.0
    min_packet_length: int = 0
    max_packet_length: int = 0
    mean_packet_length: float = 0.0
    syn_count: int = 0
    fin_count: int = 0
    rst_count: int = 0
    psh_count: int = 0
    ack_count: int = 0
    urg_count: int = 0


class MITREMapping(BaseModel):
    """MITRE ATT&CK mapping for a detection."""
    tactic: str
    technique_id: str
    technique_name: str
    sub_technique_id: Optional[str] = None
    sub_technique_name: Optional[str] = None


class Alert(BaseModel):
    """Security alert generated by the detection engines."""
    model_config = ConfigDict(from_attributes=True)

    id: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)
    severity: AlertSeverity
    detection_type: DetectionType
    attack_category: AttackCategory = AttackCategory.UNKNOWN
    description: str
    source_ip: str
    dest_ip: str
    protocol: str
    source_port: Optional[int] = None
    dest_port: Optional[int] = None
    confidence_score: Optional[float] = None
    packet_data: Optional[Dict[str, Any]] = None
    flow_id: Optional[str] = None
    mitre_mapping: Optional[MITREMapping] = None
    geo_info: Optional[Dict[str, Any]] = None
    threat_intel: Optional[Dict[str, Any]] = None
    is_resolved: bool = False
    resolved_by: Optional[str] = None
    resolved_at: Optional[datetime] = None
    resolution_notes: Optional[str] = None
    integrity_hash: Optional[str] = None
    incident_id: Optional[str] = None
    related_alert_ids: List[str] = Field(default_factory=list)


class Incident(BaseModel):
    """Correlated group of alerts representing a multi-stage attack."""
    incident_id: str
    title: str
    description: str
    severity: AlertSeverity
    attack_category: AttackCategory
    alert_ids: List[str] = Field(default_factory=list)
    source_ips: List[str] = Field(default_factory=list)
    target_ips: List[str] = Field(default_factory=list)
    first_seen: datetime
    last_seen: datetime
    is_active: bool = True
    mitre_chain: List[MITREMapping] = Field(default_factory=list)


class UserCreate(BaseModel):
    """User registration request."""
    username: str = Field(..., min_length=3, max_length=50)
    email: str
    password: str = Field(..., min_length=8)
    role: UserRole = UserRole.VIEWER


class UserLogin(BaseModel):
    """User login request."""
    username: str
    password: str


class UserResponse(BaseModel):
    """User data returned to the client."""
    id: str
    username: str
    email: str
    role: UserRole
    is_active: bool = True
    created_at: datetime
    last_login: Optional[datetime] = None


class TokenResponse(BaseModel):
    """JWT token response."""
    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    expires_in: int


class SnifferConfig(BaseModel):
    """Packet capture configuration."""
    interface: str = Field(default="eth0", description="Network interface to monitor")
    packet_count: int = Field(default=0, description="Packets to capture (0 = unlimited)")
    timeout: int = Field(default=0, description="Capture timeout in seconds (0 = infinite)")
    filter: Optional[str] = Field(default=None, description="BPF filter string")
    workers: int = Field(default=4, description="Number of capture worker processes")


class MLModelConfig(BaseModel):
    """ML model configuration."""
    model_path: str = Field(default="app/ml_models/nids_model.joblib")
    confidence_threshold: float = Field(default=0.8, ge=0.0, le=1.0)
    model_type: str = Field(
        default="random_forest",
        description="Model type: random_forest | isolation_forest | gradient_boosting | deep_learning"
    )
    feature_columns: List[str] = Field(default_factory=list)
    enable_flow_features: bool = Field(default=True)
    enable_dl_models: bool = Field(default=False)


class IPSConfig(BaseModel):
    """IPS configuration."""
    enabled: bool = False
    auto_block: bool = False
    block_duration_minutes: int = 60
    whitelist: List[str] = Field(default_factory=lambda: ["127.0.0.1", "0.0.0.0"])
    severity_threshold: AlertSeverity = AlertSeverity.CRITICAL


class SystemStatus(BaseModel):
    """System status information."""
    is_running: bool
    uptime: float
    packets_captured: int
    flows_aggregated: int = 0
    alerts_generated: int
    ml_predictions: int
    signature_matches: int
    memory_usage: float
    cpu_usage: float
    active_connections: int = 0


class ComponentHealth(BaseModel):
    """Health of an individual component."""
    name: str
    status: str  # "healthy", "degraded", "down"
    details: Optional[Dict[str, Any]] = None
    last_check: datetime = Field(default_factory=datetime.now)


class HealthResponse(BaseModel):
    """Full system health report."""
    status: str
    version: str
    components: List[ComponentHealth] = Field(default_factory=list)
    uptime_seconds: float = 0.0


class StartSnifferRequest(BaseModel):
    """Request to start packet sniffing."""
    config: Optional[SnifferConfig] = None


class StopSnifferRequest(BaseModel):
    """Request to stop packet sniffing."""
    force: bool = False


class AlertResponse(BaseModel):
    """Paginated alert response."""
    alerts: List[Alert]
    total_count: int
    page: int = 1
    page_size: int = 100


class PacketResponse(BaseModel):
    """Paginated packet response."""
    packets: List[PacketInfo]
    total_count: int
    page: int = 1
    page_size: int = 100


class StatsResponse(BaseModel):
    """System statistics response."""
    total_packets: int
    total_flows: int = 0
    total_alerts: int
    ml_detections: int
    signature_detections: int
    behavioral_detections: int = 0
    false_positives: int = 0
    detection_rate: float
    average_confidence: float


class BlockIPRequest(BaseModel):
    """Request to block an IP address."""
    ip_address: str
    duration_minutes: int = 60
    reason: str = "Manual block"
    action: IPSAction = IPSAction.BLOCK


class ThreatIntelResult(BaseModel):
    """Threat intelligence lookup result."""
    ip_address: str
    is_malicious: bool = False
    abuse_score: Optional[float] = None
    source: str = "unknown"
    country: Optional[str] = None
    isp: Optional[str] = None
    categories: List[str] = Field(default_factory=list)
    last_reported: Optional[datetime] = None
